### ISSUE TITLE
Bloggist App

### ISSUE THREAD

**Issue by adepascua1** [altimetrik-onboarding-uy/adepascua#1]
As a blogger I want a Blogging app called "Bloggist" on top of the Force.com platform in order to be able to store everything related to a Post in Salesforce.

**Comment by stefaniaoverman** [comment]
so that...?

**Comment by adepascua1** [comment]
As a blogger I want a Blogging app called "Bloggist" on top of the Force.com platform in order to be able to store everything related to a Post in Salesforce.
