### ISSUE TITLE
Bloggist - Status

### ISSUE THREAD

**Issue by adepascua1** [altimetrik-onboarding-uy/adepascua#5]
As a user i want to store the Status of the posts with the following options: 

- Draft
- Published
- Under Review
- Ready

So that's gonna identify in which stage the post are.

**Comment by stefaniaoverman** [comment]
i would say: 

As a user i want to store the Status of the posts with the following options:

Draft
Published
Under Review
Ready
In order to identify in which stage the post are.

**Comment by adepascua1** [comment]
> i would say:
> 
> As a user i want to store the Status of the posts with the following options:
> 
> Draft
> Published
> Under Review
> Ready
> In order to identify in which stage the post are.

Ok!
