### ISSUE TITLE
Bloggist - Create Post

### ISSUE THREAD

**Issue by adepascua1** [altimetrik-onboarding-uy/adepascua#6]
As a writer, I want to create new post in the writer/author section in order to be able to store the followings: Title, Published Date, Content and Status.

**Comment by stefaniaoverman** [comment]
this one needs to get a little bit better, like: (1) as ___role__,  i want xxxx, so that I can xxxx.

**Comment by adepascua1** [comment]
As a writer, I want to create new post in the writer/author section in order to be able to create and see every post I create.
